[env]
platform = espressif32
board = esp32dev              ; Altere aqui se usar outra placa (ex: esp32-s3-devkitc-1)
framework = arduino
monitor_speed = 115200

; ==============================================================================
; 1. AMBIENTE: TESTE DOS MOTORES (TMC2209)
; ==============================================================================
[env:teste_motores]
build_src_filter = 
  -<*>                        ; Ignora todos os arquivos da pasta src/
  +<teste_motores.cpp>        ; Compila APENAS o arquivo do teste de motores
lib_deps = 
  waspinator/AccelStepper @ ^1.64
  teemuatlut/TMCStepper@^0.7.3

; ==============================================================================
; 2. AMBIENTE: TESTE DO ENCODER (AS5060 / AS5600)
; ==============================================================================
[env:teste_encoder]
build_src_filter = 
  -<*>                        ; Ignora todos os arquivos da pasta src/
  +<teste_encoder.cpp>        ; Compila APENAS o arquivo do teste do encoder
lib_deps = 
  Wire                        ; Biblioteca I2C nativa do Arduino/ESP32
  robtillaart/AS5600 @ ^0.6.7  ; Biblioteca para encoders magnéticos I2C da AMS

; ==============================================================================
; 3. AMBIENTE: APLICAÇÃO PRINCIPAL (MAIN)
; ==============================================================================
[env:main]
build_src_filter = 
  -<*>                        ; Ignora todos os arquivos da pasta src/
  +<main.cpp>                 ; Compila APENAS o programa principal
  +<Eixo.cpp>
  +<WebController.cpp>

lib_deps = 
  waspinator/AccelStepper @ ^1.64
  teemuatlut/TMCStepper @ ^0.7.3
  Wire
  robtillaart/AS5600 @ ^0.6.7